### ISSUE TITLE
Abschneiden von Namen bei Itemvergabe

### ISSUE THREAD

**Issue by Sn4ck3rS** [INCRD/IncendioLoot#52]
**Beschreibe den Bug**
Bei der Itemvergabe an wen das Item ging werden einige Namen abgeschnitten im Chat. Beispiele: Baaemm -> mm, Bremnos -> remnos, Astrasu -> strasu. Gegenbeispiele: Xelzos -> Xelzos, Yizzy -> Yizzy
Gleichbleibend bei den Namen (also Baaemm wird IMMER zu mm).

**Nachstellen**
Schreibe die Schritte, um den Bug nachzustellen:
1. Item über IncendioLoot zuweisen
2. Auf den Chat achten :D

**Screenshots**
-glaub den brauchst du nicht- (hab auch grad keinen)

**Comment by INCRD** [comment]
Mit der letzten Version gelöst
